### ISSUE TITLE
Update extension on extensions.gnome.org

### ISSUE THREAD

**Issue by rogama25** [kennedn/gnome-shell-extension-spotify-controls#5]
Extension was already fixed for GNOME 42 (https://github.com/kennedn/gnome-shell-extension-mprispanel/pull/4), please update the extension on extensions.gnome.org, because it still shows as unavailable: https://extensions.gnome.org/extension/4088/mpris-panel-player/

**Comment by kennedn** [comment]
I did so shortly after the version bump and the submission was rejected with the following comment:

> Any timeout you are adding in extension.js should be removed on disable:
> https://gjs.guide/extensions/review-guidelines/review-guidelines.html#remove-main-loop-sources
> If you need any help with your extension you can ask us on:
> - [GNOME Matrix Channel](https://matrix.to/#/#extensions:gnome.org)
> - IRC Bridge: irc://irc.gimpnet.org/shell-extensions

This sort of comment is fairly typical on submission and I do not have the time to pursue this sort of rework on every version bump. I suspect it is why there are many dead extensions on extensions.gnome.org.

I do have a plan to refactor the extension to use the 'NameOwnerChanged' dbus signal to detect new players as apposed to the current GLib.timeout_add polling solution. I will endeavor to get another submission through code review if and when this refactor ever manifests.
